Synced with abot-rel-2

diff --git a/abot-epc-basic/hooks/config-changed b/abot-epc-basic/hooks/config-changed
--- a/abot-epc-basic/hooks/config-changed
+++ b/abot-epc-basic/hooks/config-changed
@@ -18,9 +18,20 @@ if [ -n $TAG_DIR/tags ]; then
         echo -n "@$tags" > $TAG_DIR/tags
 fi
 
-ip=$(unit-get public-address)
-#ip=`dig +short $ip`
-
+private_address=$(unit-get private-address)
+if [[ `dig +short $private_address` =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
+then
+    juju-log "Verifying $private_address in dns "
+    DIGSHORT="dig +short"
+elif [[  "$private_address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
+then
+    DIGSHORT=echo
+else
+    juju-log "Unable to fetch private_address ..."
+    exit 1
+fi
+ip=`$DIGSHORT $private_address`
+  
 if [ ! -z $ip ]; then
     sed -i "s/ABOT.Host.IPAddress=[^ ]*/ABOT.Host.IPAddress=$ip/" $CHARM_DIR/lib/config/config.properties
     sed -i "s#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1_MME=[^ ]*#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1_MME=$ip/24#" $CHARM_DIR/lib/config/epc_defaults.conf
